### ISSUE TITLE
Converting surface normals RGB to world angles

### ISSUE THREAD

**Issue by srama2512** [EPFL-VILAB/XTConsistency#2]
Thank you for this wonderful repository! I'm trying to convert the surface normal predictions to real world angles. Specifically, I want to convert the `3 x H x W` image with values in [0., 1.] to `2 x H x W` array with the 2 channels corresponding to the angles in radians. Could you suggest the best way to do this?

**Comment by alexsax** [comment]
Hi @srama2512,

The models were trained on the Taskonomy dataset, and in those datasets the RGB values of the surface normals correspond to the three coordinates of the surface normal vector as in the [2D3DSemantic](https://github.com/alexsax/2D-3D-Semantics) or [Taskonomy](https://github.com/StanfordVL/taskonomy/tree/master/data) datasets. Note that estimating the actual direction in world coordinates would be ill-posed from a single image, and so the direction is relative to the camera. 

The direction of the vector can be found from the RGB with (I believe) red corresponding to more right, green corresponding to more down, and blue corresponding to how much the vector points back at the camera. 

- So to find the actual coordinates of the unit normal vector with RGB values = `(R, G, B)`, do 
`(x, y, z) = ((R - 127.5) / 127.5, (G - 127.5) / 127.5,  (B - 127.5) / 127.5)`. I believe the networks output a value in [0, 1] instead of [0, 255], so to convert raw network outputs do `(x, y, z) = ((R - 0.5), (G - 0.5),  (B - 0.5))`. Then you can find angles from this vector based on the usual vector angle formulas.
